/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author josejailtonjunior
 */
import java.awt.CardLayout;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import javax.swing.JOptionPane;
import java.util.ArrayList;

public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        base = new javax.swing.JPanel();
        inicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Bt_Cad_Alu = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        Bt_Cad_Prof = new javax.swing.JButton();
        Bt_Cad_Livro = new javax.swing.JButton();
        Cad_Alu = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TxtRec_Mat1 = new javax.swing.JTextField();
        TxtRec_Nome1 = new javax.swing.JTextField();
        BtCad1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        TxtRec_CPF1 = new javax.swing.JTextField();
        TxtRec_RG1 = new javax.swing.JTextField();
        TxtRec_End1 = new javax.swing.JTextField();
        TxtRec_DN1 = new javax.swing.JTextField();
        TxtRec_Cidade1 = new javax.swing.JTextField();
        TxtRec_Bairro1 = new javax.swing.JTextField();
        BtVoltar2 = new javax.swing.JButton();
        Cad_Livro = new javax.swing.JPanel();
        H1 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Cad_Prof = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtRec_Titula = new javax.swing.JTextField();
        TxtRec_Nome = new javax.swing.JTextField();
        BtCad = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TxtRec_CPF = new javax.swing.JTextField();
        TxtRec_RG = new javax.swing.JTextField();
        TxtRec_End = new javax.swing.JTextField();
        TxtRec_DN = new javax.swing.JTextField();
        TxtRec_Cidade = new javax.swing.JTextField();
        TxtRec_Bairro = new javax.swing.JTextField();
        BtVoltar = new javax.swing.JButton();
        consultar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        BtVoltar1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        Menu_Item_CadAlu = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Menu_Item_CadProf = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        base.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Estruturas de Dados");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("UFPA - Castanhal");

        Bt_Cad_Alu.setText("Cadastrar Aluno");
        Bt_Cad_Alu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Cad_AluActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Exotc350 Bd BT", 0, 36)); // NOI18N
        jLabel15.setText("O que deseja fazer?");

        Bt_Cad_Prof.setText("Cadastrar Professor");
        Bt_Cad_Prof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Cad_ProfActionPerformed(evt);
            }
        });

        Bt_Cad_Livro.setText("Cadastrar Livro");
        Bt_Cad_Livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Cad_LivroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inicioLayout = new javax.swing.GroupLayout(inicio);
        inicio.setLayout(inicioLayout);
        inicioLayout.setHorizontalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inicioLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(16, 16, 16)))
                .addGap(197, 197, 197))
            .addGroup(inicioLayout.createSequentialGroup()
                .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inicioLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel15))
                    .addGroup(inicioLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Bt_Cad_Alu)
                        .addGap(18, 18, 18)
                        .addComponent(Bt_Cad_Prof)
                        .addGap(18, 18, 18)
                        .addComponent(Bt_Cad_Livro)))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        inicioLayout.setVerticalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(95, 95, 95)
                .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bt_Cad_Alu)
                    .addComponent(Bt_Cad_Prof)
                    .addComponent(Bt_Cad_Livro))
                .addContainerGap(272, Short.MAX_VALUE))
        );

        base.add(inicio, "inicio");

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel16.setText("Cadastrar Aluno");

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel17.setText("Matrícula:");

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel18.setText("CPF");

        TxtRec_Mat1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        TxtRec_Mat1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtRec_Mat1KeyTyped(evt);
            }
        });

        TxtRec_Nome1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        TxtRec_Nome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRec_Nome1ActionPerformed(evt);
            }
        });
        TxtRec_Nome1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtRec_Nome1KeyTyped(evt);
            }
        });

        BtCad1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        BtCad1.setText("Cadastrar");
        BtCad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCad1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel19.setText("Nome:");

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel20.setText("RG");

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel21.setText("Data de nascimento");

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel22.setText("Endereço");

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel23.setText("Cidade");

        jLabel24.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel24.setText("Bairro");

        TxtRec_CPF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtRec_CPF1KeyTyped(evt);
            }
        });

        TxtRec_RG1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtRec_RG1KeyTyped(evt);
            }
        });

        TxtRec_DN1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtRec_DN1KeyTyped(evt);
            }
        });

        TxtRec_Cidade1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtRec_Cidade1KeyTyped(evt);
            }
        });

        TxtRec_Bairro1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtRec_Bairro1KeyTyped(evt);
            }
        });

        BtVoltar2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        BtVoltar2.setText("Voltar");
        BtVoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVoltar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Cad_AluLayout = new javax.swing.GroupLayout(Cad_Alu);
        Cad_Alu.setLayout(Cad_AluLayout);
        Cad_AluLayout.setHorizontalGroup(
            Cad_AluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cad_AluLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Cad_AluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Cad_AluLayout.createSequentialGroup()
                        .addGroup(Cad_AluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel19)
                            .addComponent(TxtRec_End1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Cad_AluLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtRec_DN1)
                                .addGap(171, 171, 171)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Cad_AluLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtRec_CPF1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtRec_RG1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Cad_AluLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(Cad_AluLayout.createSequentialGroup()
                .addGroup(Cad_AluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Cad_AluLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Cad_AluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(Cad_AluLayout.createSequentialGroup()
                                .addComponent(BtVoltar2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtCad1))
                            .addGroup(Cad_AluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(Cad_AluLayout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addGap(18, 18, 18)
                                    .addGroup(Cad_AluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TxtRec_Nome1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TxtRec_Mat1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(Cad_AluLayout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TxtRec_Cidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel24)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TxtRec_Bairro1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(Cad_AluLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel16)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        Cad_AluLayout.setVerticalGroup(
            Cad_AluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cad_AluLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Cad_AluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(TxtRec_Mat1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Cad_AluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Cad_AluLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel19))
                    .addGroup(Cad_AluLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TxtRec_Nome1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(Cad_AluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Cad_AluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(TxtRec_CPF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Cad_AluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(TxtRec_RG1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Cad_AluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(TxtRec_DN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(TxtRec_End1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Cad_AluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(TxtRec_Cidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtRec_Bairro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(Cad_AluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtCad1)
                    .addComponent(BtVoltar2))
                .addGap(21, 21, 21))
        );

        base.add(Cad_Alu, "Cad_Alu");

        H1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        H1.setText("Cadastrar livro");

        Titulo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Titulo.setText("Titulo");

        jLabel25.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel25.setText("Autor");

        jLabel26.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel26.setText("Editora");

        jLabel27.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel27.setText("Quantidade");

        jLabel28.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel28.setText("Codigo");

        jButton1.setText("Cadastrar Livro");

        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Cad_LivroLayout = new javax.swing.GroupLayout(Cad_Livro);
        Cad_Livro.setLayout(Cad_LivroLayout);
        Cad_LivroLayout.setHorizontalGroup(
            Cad_LivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cad_LivroLayout.createSequentialGroup()
                .addGroup(Cad_LivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(Cad_LivroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(Cad_LivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Cad_LivroLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(Titulo))
                        .addGroup(Cad_LivroLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel26))
                        .addGroup(Cad_LivroLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel27))
                        .addGroup(Cad_LivroLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel28))
                        .addGroup(Cad_LivroLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel25))
                        .addGroup(Cad_LivroLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Cad_LivroLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Cad_LivroLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Cad_LivroLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Cad_LivroLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Cad_LivroLayout.createSequentialGroup()
                            .addGap(184, 184, 184)
                            .addComponent(H1))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        Cad_LivroLayout.setVerticalGroup(
            Cad_LivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cad_LivroLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(H1)
                .addGap(18, 18, 18)
                .addComponent(Titulo)
                .addGap(8, 8, 8)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(Cad_LivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        base.add(Cad_Livro, "Cad_Livro");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setText("Cadastrar Professor");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("Titulação");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("CPF");

        TxtRec_Titula.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        TxtRec_Titula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtRec_TitulaKeyTyped(evt);
            }
        });

        TxtRec_Nome.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        TxtRec_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRec_NomeActionPerformed(evt);
            }
        });
        TxtRec_Nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtRec_NomeKeyTyped(evt);
            }
        });

        BtCad.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        BtCad.setText("Cadastrar");
        BtCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setText("Nome:");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setText("RG");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel11.setText("Data de nascimento");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel12.setText("Endereço");

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel13.setText("Cidade");

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel14.setText("Bairro");

        TxtRec_CPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtRec_CPFKeyTyped(evt);
            }
        });

        TxtRec_RG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtRec_RGKeyTyped(evt);
            }
        });

        TxtRec_DN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtRec_DNKeyTyped(evt);
            }
        });

        TxtRec_Cidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtRec_CidadeKeyTyped(evt);
            }
        });

        TxtRec_Bairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtRec_BairroKeyTyped(evt);
            }
        });

        BtVoltar.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        BtVoltar.setText("Voltar");
        BtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Cad_ProfLayout = new javax.swing.GroupLayout(Cad_Prof);
        Cad_Prof.setLayout(Cad_ProfLayout);
        Cad_ProfLayout.setHorizontalGroup(
            Cad_ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cad_ProfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Cad_ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Cad_ProfLayout.createSequentialGroup()
                        .addGroup(Cad_ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Cad_ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(Cad_ProfLayout.createSequentialGroup()
                                    .addComponent(BtVoltar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtCad))
                                .addGroup(Cad_ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Cad_ProfLayout.createSequentialGroup()
                                        .addGroup(Cad_ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(Cad_ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxtRec_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtRec_Titula, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(Cad_ProfLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtRec_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtRec_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel12)
                            .addGroup(Cad_ProfLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtRec_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtRec_RG, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Cad_ProfLayout.createSequentialGroup()
                        .addGroup(Cad_ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Cad_ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TxtRec_End, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(Cad_ProfLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TxtRec_DN)
                                    .addGap(171, 171, 171)))
                            .addGroup(Cad_ProfLayout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        Cad_ProfLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {TxtRec_Nome, TxtRec_Titula});

        Cad_ProfLayout.setVerticalGroup(
            Cad_ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cad_ProfLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Cad_ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtRec_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(Cad_ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtRec_Titula, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(Cad_ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(TxtRec_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtRec_RG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Cad_ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TxtRec_DN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TxtRec_End, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Cad_ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(TxtRec_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtRec_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(Cad_ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtCad)
                    .addComponent(BtVoltar))
                .addGap(21, 21, 21))
        );

        Cad_ProfLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {TxtRec_Nome, TxtRec_Titula});

        base.add(Cad_Prof, "Cad_Prof");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel6.setText("Consultar");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel7.setText("Matrícula:");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel8.setText("Nome:");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton2.setText("Consultar");

        BtVoltar1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        BtVoltar1.setText("Voltar");
        BtVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVoltar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consultarLayout = new javax.swing.GroupLayout(consultar);
        consultar.setLayout(consultarLayout);
        consultarLayout.setHorizontalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarLayout.createSequentialGroup()
                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consultarLayout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel6))
                    .addGroup(consultarLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(consultarLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jButton2))
                    .addGroup(consultarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtVoltar1)))
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(consultarLayout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel8)
                    .addContainerGap(537, Short.MAX_VALUE)))
        );
        consultarLayout.setVerticalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consultarLayout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addComponent(jLabel7))
                .addGap(25, 25, 25)
                .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addGap(89, 89, 89)
                .addComponent(jButton2)
                .addGap(139, 139, 139)
                .addComponent(BtVoltar1)
                .addGap(25, 25, 25))
            .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(consultarLayout.createSequentialGroup()
                    .addGap(127, 127, 127)
                    .addComponent(jLabel8)
                    .addContainerGap(404, Short.MAX_VALUE)))
        );

        base.add(consultar, "consultar");

        jMenu1.setText("Arquivo");

        jMenu2.setText("Aluno");

        Menu_Item_CadAlu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Menu_Item_CadAlu.setText("Cadastrar");
        Menu_Item_CadAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Item_CadAluActionPerformed(evt);
            }
        });
        jMenu2.add(Menu_Item_CadAlu);

        jMenuItem2.setText("Alterar informações");
        jMenu2.add(jMenuItem2);

        jMenuItem4.setText("Remover");
        jMenu2.add(jMenuItem4);

        jMenuItem13.setText("Consultar");
        jMenu2.add(jMenuItem13);

        jMenu1.add(jMenu2);

        jMenu3.setText("Professor");

        Menu_Item_CadProf.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Menu_Item_CadProf.setText("Cadastrar");
        Menu_Item_CadProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Item_CadProfActionPerformed(evt);
            }
        });
        jMenu3.add(Menu_Item_CadProf);

        jMenuItem6.setText("Alterar");
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Remover");
        jMenu3.add(jMenuItem7);

        jMenu1.add(jMenu3);

        jMenu4.setText("Biblioteca");

        jMenuItem8.setText("Cadastrar");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuItem9.setText("Emprestar");
        jMenu4.add(jMenuItem9);

        jMenuItem10.setText("Consultar");
        jMenu4.add(jMenuItem10);

        jMenuItem11.setText("Devolução");
        jMenu4.add(jMenuItem11);

        jMenu1.add(jMenu4);

        jMenuItem12.setText("Bolsista");
        jMenu1.add(jMenuItem12);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtCadActionPerformed

    private void TxtRec_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRec_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRec_NomeActionPerformed

    private void TxtRec_TitulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRec_TitulaKeyTyped
                // TODO add your handling code here:
        String valores = "0123456789";
        if(!valores.contains(evt.getKeyChar()+"")){
        evt.consume();
        }
    }//GEN-LAST:event_TxtRec_TitulaKeyTyped

    private void TxtRec_NomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRec_NomeKeyTyped
        // TODO add your handling code here:
        String valores = "0123456789@!#$%^&*";
        if(valores.contains(evt.getKeyChar()+"")){
        evt.consume();
        }
    }//GEN-LAST:event_TxtRec_NomeKeyTyped

    private void Menu_Item_CadAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Item_CadAluActionPerformed
        // TODO add your handling code here:
            CardLayout tela = (CardLayout) base.getLayout();
            tela.show(base, "Cad_Alu");
    }//GEN-LAST:event_Menu_Item_CadAluActionPerformed

    private void Bt_Cad_AluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Cad_AluActionPerformed
        // TODO add your handling code here:
            CardLayout tela = (CardLayout) base.getLayout();
            tela.show(base, "Cad_Alu");
    }//GEN-LAST:event_Bt_Cad_AluActionPerformed

    private void BtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVoltarActionPerformed
        // TODO add your handling code here:
        CardLayout tela = (CardLayout) base.getLayout();
            tela.show(base, "inicio");
    }//GEN-LAST:event_BtVoltarActionPerformed

    private void BtVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVoltar1ActionPerformed
        // TODO add your handling code here:
            CardLayout tela = (CardLayout) base.getLayout();
            tela.show(base, "inicio");
    }//GEN-LAST:event_BtVoltar1ActionPerformed

    private void TxtRec_CPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRec_CPFKeyTyped
        // TODO add your handling code here:
        String valores = "0123456789";
        if(!valores.contains(evt.getKeyChar()+"")){
        evt.consume();
        }
    }//GEN-LAST:event_TxtRec_CPFKeyTyped

    private void TxtRec_RGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRec_RGKeyTyped
        // TODO add your handling code here:
        String valores = "0123456789";
        if(!valores.contains(evt.getKeyChar()+"")){
        evt.consume();
        }
    }//GEN-LAST:event_TxtRec_RGKeyTyped

    private void TxtRec_DNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRec_DNKeyTyped
        // TODO add your handling code here:
        String valores = "0123456789";
        if(!valores.contains(evt.getKeyChar()+"")){
        evt.consume();
        }
    }//GEN-LAST:event_TxtRec_DNKeyTyped

    private void TxtRec_CidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRec_CidadeKeyTyped
        // TODO add your handling code here:
        String valores = "0123456789@!#$%^&*";
        if(valores.contains(evt.getKeyChar()+"")){
        evt.consume();
        }
    }//GEN-LAST:event_TxtRec_CidadeKeyTyped

    private void TxtRec_BairroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRec_BairroKeyTyped
        // TODO add your handling code here:
        String valores = "0123456789@!#$%^&*";
        if(valores.contains(evt.getKeyChar()+"")){
        evt.consume();
        }
    }//GEN-LAST:event_TxtRec_BairroKeyTyped

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void TxtRec_Mat1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRec_Mat1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRec_Mat1KeyTyped

    private void TxtRec_Nome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRec_Nome1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtRec_Nome1ActionPerformed

    private void TxtRec_Nome1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRec_Nome1KeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtRec_Nome1KeyTyped

    private void BtCad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtCad1ActionPerformed

    private void TxtRec_CPF1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRec_CPF1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRec_CPF1KeyTyped

    private void TxtRec_RG1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRec_RG1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRec_RG1KeyTyped

    private void TxtRec_DN1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRec_DN1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRec_DN1KeyTyped

    private void TxtRec_Cidade1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRec_Cidade1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRec_Cidade1KeyTyped

    private void TxtRec_Bairro1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRec_Bairro1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRec_Bairro1KeyTyped

    private void BtVoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVoltar2ActionPerformed
        // TODO add your handling code here:
        CardLayout tela = (CardLayout) base.getLayout();
        tela.show(base, "inicio");
    }//GEN-LAST:event_BtVoltar2ActionPerformed

    private void Menu_Item_CadProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Item_CadProfActionPerformed
        // TODO add your handling code here:
        CardLayout tela = (CardLayout) base.getLayout();
            tela.show(base, "Cad_Prof");
    }//GEN-LAST:event_Menu_Item_CadProfActionPerformed

    private void Bt_Cad_ProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Cad_ProfActionPerformed
        // TODO add your handling code here:
        CardLayout tela = (CardLayout) base.getLayout();
            tela.show(base, "Cad_Prof");
    }//GEN-LAST:event_Bt_Cad_ProfActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CardLayout tela = (CardLayout) base.getLayout();
            tela.show(base, "inicio");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        CardLayout tela = (CardLayout) base.getLayout();
            tela.show(base, "Cad_Livro");
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void Bt_Cad_LivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Cad_LivroActionPerformed
        // TODO add your handling code here:
        CardLayout tela = (CardLayout) base.getLayout();
            tela.show(base, "Cad_Livro");
        
    }//GEN-LAST:event_Bt_Cad_LivroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCad;
    private javax.swing.JButton BtCad1;
    private javax.swing.JButton BtVoltar;
    private javax.swing.JButton BtVoltar1;
    private javax.swing.JButton BtVoltar2;
    private javax.swing.JButton Bt_Cad_Alu;
    private javax.swing.JButton Bt_Cad_Livro;
    private javax.swing.JButton Bt_Cad_Prof;
    private javax.swing.JPanel Cad_Alu;
    private javax.swing.JPanel Cad_Livro;
    private javax.swing.JPanel Cad_Prof;
    private javax.swing.JLabel H1;
    private javax.swing.JMenuItem Menu_Item_CadAlu;
    private javax.swing.JMenuItem Menu_Item_CadProf;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField TxtRec_Bairro;
    private javax.swing.JTextField TxtRec_Bairro1;
    private javax.swing.JTextField TxtRec_CPF;
    private javax.swing.JTextField TxtRec_CPF1;
    private javax.swing.JTextField TxtRec_Cidade;
    private javax.swing.JTextField TxtRec_Cidade1;
    private javax.swing.JTextField TxtRec_DN;
    private javax.swing.JTextField TxtRec_DN1;
    private javax.swing.JTextField TxtRec_End;
    private javax.swing.JTextField TxtRec_End1;
    private javax.swing.JTextField TxtRec_Mat1;
    private javax.swing.JTextField TxtRec_Nome;
    private javax.swing.JTextField TxtRec_Nome1;
    private javax.swing.JTextField TxtRec_RG;
    private javax.swing.JTextField TxtRec_RG1;
    private javax.swing.JTextField TxtRec_Titula;
    private javax.swing.JPanel base;
    private javax.swing.JPanel consultar;
    private javax.swing.JPanel inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
